version: 2
jobs:
  build:
    working_directory: ~/kotlin-graphql-sample
    docker:
    - image: circleci/openjdk:10-jdk

    steps:
    - checkout

    - restore_cache:
        keys:
        - v1-build-dependencies-{{ checksum "settings.gradle.kts" }}-{{ checksum "build.gradle.kts" }}-{{ checksum "gradle.properties" }}

    - run:
        name: Jar作成
        command: ./gradlew ktlintCheck bootJar --no-daemon --max-workers 2

    - save_cache:
        paths:
        - ~/.gradle/caches
        - ~/.gradle/wrapper
        key: v1-build-dependencies-{{ checksum "settings.gradle.kts" }}-{{ checksum "build.gradle.kts" }}-{{ checksum "gradle.properties" }}

    - store_artifacts:
        path: ./build/libs/

  test:
    working_directory: ~/kotlin-graphql-sample
    docker:
      - image: circleci/openjdk:10-jdk
        environment:
          SPRING_DATASOURCE_URL: "jdbc:postgresql://localhost:5435/postgres"
      - image: postgres:9.6.6-alpine
        environment:
          POSTGRES_USER: postgres
          POSTGRES_DB: postgres
    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-test-dependencies-{{ checksum "settings.gradle.kts" }}-{{ checksum "build.gradle.kts" }}-{{ checksum "gradle.properties" }}

      - run:
          name: テスト
          command: ./gradlew test jacocoTestReport --no-daemon --max-workers 2

      - store_test_results:
          path: build/test-results

      - store_artifacts:
          path: build/test-results

      - store_artifacts:
          path: build/reports

      - save_cache:
          paths:
          - ~/.gradle/caches
          - ~/.gradle/wrapper
          key: v1-test-dependencies-{{ checksum "settings.gradle.kts" }}-{{ checksum "build.gradle.kts" }}-{{ checksum "gradle.properties" }}

workflows:
  version: 2
  build_and_test:
    jobs:
    - build
    - test